### ISSUE TITLE
un peu

### ISSUE THREAD

**Issue by sylvainkahane** [surfacesyntacticud/guidelines#10]
We don't have the same analysis of "un peu" in GSD and Spoken.
http://match.grew.fr/?corpus=SUD_French-GSD@latest&custom=5fafbcc57dae4
http://match.grew.fr/?corpus=SUD_French-Spoken@latest&custom=5fafb9b1dd830

Even if "peu" is an ADV un "j'ai peu mangé", I think it make sens to analyse it as a NOUN in some other expessions: un peu, un petit peu, quelque peu, pour le peu que, etc.

Are you ok to align the analysis of un peu in GSD to the one in Spoken?

![image](https://user-images.githubusercontent.com/23051796/99145911-352a6f00-2673-11eb-9a96-266974195ee5.png)

**Comment by bguil** [comment]
This is consistent with the analysis given in [Wiktionary](https://fr.wiktionary.org/wiki/peu) in which *peu* may be:

 * a [common noun](https://fr.wiktionary.org/wiki/peu#fr-nom-1): *le peu de*, *un peu*, *un peu de…*
 * an [adverb](https://fr.wiktionary.org/wiki/peu#fr-adv-1): *Ce film est peu intéressant*

But, if we want to follow the Wiktionary analysis, there is also:

 * [pronoun](https://fr.wiktionary.org/wiki/peu#Pronom_ind%C3%A9fini): *peu de gens*, *peu de chose*

The current **SUD_French-GSD** annotation uses some `upos`+`ExtPos` annotation to handle this. The [request](http://match.grew.fr/?corpus=SUD_French-GSD@latest&custom=5fb26f455b004&clustering=N.lemma) gives examples where `ExtPos` is used nor in an idiom neither in title. This covers examples like *peu de* or *beaucoup de*.

I propose to follow Wiktionary on all occurrence of *peu* (and *beaucoup* to be consistent) and to avoid as much as possible `ExtPos` on a "single" token.

NB: **SUD_French-Spoken** already uses `PRON` in the majority (but not all) of occurrences of *beaucoup de*: [Grew-match](http://match.grew.fr/?corpus=SUD_French-Spoken@latest&custom=5fb271ec81a29&clustering=N1.upos).

**Comment by sylvainkahane** [comment]
ok to use PRON for construction such as _peu de N_. Il will also concern _plein de N_, _nombre de N_, etc.

An additional reason for doing that is that these words can be used without _de N_: _peu sont venus_, _plein m'ont répondu_, etc.

**Comment by emmettstr** [comment]
These seem like sensible proposals to me, but what about an utterance like _très peu sont venus à la soirée_, where peu is modified by an adverb? Would the PRON label hold water in this context?

**Comment by sylvainkahane** [comment]
@emmettstr Excellent remark!
So upos=ADV + ExtPos=PRON is not so bad. Same thing for others: _beaucoup trop de gens sont venus_, _pas moins de 20 personnes sont venues_, etc.
Even _beaucoup_ should be annotated upos=ADV + ExtPos=PRON, because we have _vraiment beaucoup de gens sont venus_ or _pas beaucoup de gens sont venus_.

**Comment by perrier54** [comment]
Ok for using upos=ADV + ExtPos=PRON with "beaucoup de ", "peu de" ...
and NOUN with "un peu"

**Comment by bguil** [comment]
Ok with @perrier54. In fact, GSD is already annotated this way for *beaucoup de* or *peu de* ([Grew-match](http://match.grew.fr/?corpus=SUD_French-GSD@latest&custom=5fb26f455b004&clustering=N.lemma)).

But this means that we decide to generalise the usage of `ExtPos` feature to more than idiom and titles.
I think, it will be interesting to write somewhere in detail the SUD usages of `ExtPos`:
 * titles
 * idiom
 * this thread (motivated by the @emmettstr's remark)
 * @perrier54's annotation of `SYM` in GSD ([Grew-match](http://match.grew.fr/?corpus=SUD_French-GSD@latest&custom=5fb3c73136f63&clustering=N.ExtPos))

**Comment by sylvainkahane** [comment]
NUM could be concerned too, when the numeral is used as a noun (_in 2020_, _line 7_) or as a pronoun (_ces deux-là_, _j'en ai acheté 20_).
