### ISSUE TITLE
a-t-il

### ISSUE THREAD

**Issue by sylvainkahane** [surfacesyntacticud/guidelines#12]
Only GSD has PART, which is used for "-t" as well as some occurrences of "ci" and "là".
http://match.grew.fr/?corpus=SUD_French-GSD@latest&custom=5fafcdafd9412&clustering=N.form

Concerning "ci" and "là" it seems better to analyse them as ADV, which is already the case in GSD for most cases.

For "-t", Spoken considers "-t-il" as an allomorph of "il" and "-il". It is questionnable, but what is sure is that "-t" is no a syntactic element. It is a morphophonological rule that introduces the sound /t/.
Are you ok to align GSD with Spoken?

**Comment by bguil** [comment]
I agree with @sylvainkahane about the "-t" analysis. This correspond also to the analyses chosen in the French TreeBank and in Sequoia ([examples](http://match.grew.fr/?corpus=Sequoia_S@current&custom=5fb247d263241)).

For the form "-là", it is already [annotated ADV](http://match.grew.fr/?corpus=SUD_French-GSD@latest&custom=5fb24934ce2d9&clustering=N.upos). It will be more consistent to annotate all suffixes "là" and "ci" as adverbs.

Note that, in the end, it means that there is no `PART` in French.

**Comment by bguil** [comment]
Maybe, we should do the same with _l'on_ which is equivalent to _on_ and where the _l'_ is a "phonological" token?

**Comment by perrier54** [comment]
I agree with the previous proposals but this means that we have to change the tokenisation for `-t` and `l'`in [SUD_French-GSD](https://github.com/surfacesyntacticud/SUD_French-GSD).

**Comment by bguil** [comment]
I can take care about the updating of SUD_French-GSD, (an also Sequoia, PUD and FQB).

By the way, in GSD the suffix `-là` has a different analysis for `celui-là`, `ceux-là`, `jusque-là` and for other usage ([Grew-match](http://match.grew.fr/?corpus=SUD_French-GSD@latest&custom=5fb3c1c4248d2&clustering=N.form)). Do we keep this analysis?

**Comment by sylvainkahane** [comment]
I prefer an homogeneous analysis of _-là_. In Spoken all _-là_ are analyzed as independent words.
http://match.grew.fr/?corpus=SUD_French-Spoken@latest&custom=5fb3c66c7cd12&clustering=N.form

_jusque-là_ is particular, because it is the true locative _là_. which must be `comp:obj `of _jusque_.

**Comment by bguil** [comment]
Done in SUD_French-GSD and UD_French-PUD

**Comment by bguil** [comment]
Done also in Sequoia and FQB
