### ISSUE TITLE
puis

### ISSUE THREAD

**Issue by sylvainkahane** [surfacesyntacticud/guidelines#15]
"puis" is always `cc` or combined with "et":
http://match.grew.fr/?corpus=SUD_French-GSD@latest&custom=5fb3fc009c350&clustering=e.label
but it is analyzed ADV. It should be CCONJ.
Spoken is also incoherent:
http://match.grew.fr/?corpus=SUD_French-Spoken@latest&custom=5fb3fcd96134c&clustering=N.upos

**Comment by MariamNakhle** [comment]
It has been updated in SUD_French-Paris-Stories and SUD_French-Spoken.

**Comment by bguil** [comment]
Now consistent with GSD + Sequoia
