### ISSUE TITLE
wordfom

### ISSUE THREAD

**Issue by bguil** [surfacesyntacticud/guidelines#22]
We use the feature `wordform` both for normalising written form (uncapitalize the first word of a sentence for instance) and for typo correction.

But in a few cases, both are needed and there is no nice way to annotate the data.

<img width="1508" alt="487" src="https://user-images.githubusercontent.com/687155/133226338-f2719b32-9f67-448f-a29a-5530d7a35eca.png">

I propose to use a feature `CorrectForm` for typo corrections. In the example above, we would have:

```
1	Tous	tout	ADJ	_	Gender=Masc|Number=Plur|Typo=Yes	3	mod	_	CorrectForm=Tout|CorrectNumber=Sing|wordform=tous
```

**Comment by perrier54** [comment]
I agree with @bguil proposal.
