### ISSUE TITLE
conversion of disfluencies

### ISSUE THREAD

**Issue by sylvainkahane** [surfacesyntacticud/guidelines#24]
For some disfluencies we use the extension @scrap which is not correctly converted in UD.
Conversion of a comp:obj@scrap pointing on a DET (il mange le …) or on a SCONJ (il sait que …) gives a dep:comp, rather than obj or ccomp.
Moreover it would be nice to keep the @scrap feature, by translating it on a Scrap=Yes on the dependent.
http://match.grew.fr/?corpus=SUD_French-Rhapsodie@latest&custom=614b45a493da6&clustering=e.label

**Comment by bguil** [comment]
Ok, and which relation to use for [this example](http://match.grew.fr/?corpus=SUD_French-Rhapsodie@latest&custom=614c7706d8125) in UD? I guess it should be a `case` from *la* to *dans*.

**Comment by sylvainkahane** [comment]
Yes it must be a `case` and the feature Scrap=Yes must be on the head when the relation is reversed.

**Comment by bguil** [comment]
Fixed in https://github.com/surfacesyntacticud/tools/commit/21dc9fe61897776f3652146f2f71af57e63cad3f and updates in Grew-match
