### ISSUE TITLE
@x vs Generic/Raising

### ISSUE THREAD

**Issue by sylvainkahane** [surfacesyntacticud/guidelines#29]
`@x` has been introduced to be able to get back the UD distinction between `xcomp` and `ccomp`. 
Nevertheless for an infinitive verb in a dependent position, the default case is to be `@x`. It would be better to encode the particular case where there is no raising and the logical subject of the infinitive has a generic interpretation.
I suggest to replace the `@x` feature on the relation by a feature on the verb itself. I don't know how to name this feature. It could be `Raising=Yes|No` or `Generic=Yes|No` or `Subject=Raising|Generic`. It could even possible to be more precise and to precise if it is `SubjRaising`, `ObjRaising`, or `OblRaising`:
```
Subject=SubjRaising: Peter wants to leave
Subject=ObjRaising: Peter wants Mary to leave
Subject=OblRaising: Pierre propose à Marie de venir
Object=SubjRaising, Subject=Generic: the book is tough to read
Subject=Generic: it is impossible to leave
```
If we only indicate `Raising` vs `Generic`, it can be done by a Grew rule.

**Comment by perrier54** [comment]
I dont' understand the advantage of replacing `@x` attached to the dependency from the main verb to the complement verb giving rise to raising with a feature attached to the main verb, because it is equivalent. 

On the other hand, I see the disadvantage because `@x`is also used with  `mod`. 
For example:  _Melanie will call me to confirm your lie._.   _call_ `-[mod@x]->` _to_

In this case, it makes no sense to attach a feature to the verb _call_.

**Comment by sylvainkahane** [comment]
In your example, the feature would be added on the infinitive verb _confirm_.
There are several advantages:
1) in SUD the @x feature is on the relation _call_ -[mod]-> _to_, while it is above all a property of the infinitive _confirm_, whose logical subject is _me_
2) the default case for an infinitive is the raising case. For this reason it is better to indicate when the subject is generic, if we consider the generic vs raising property to be important. I suppose that @x has been forgotten in some examples.
3) if we note the raising it would be interesting to note if it is a subject or object raising (cf. _Pierre promet à Marie de venir_ vs _Pierre permet à Marie de venir_)
4) we can extend the annotation to the object raising: _the book is tough to read_

**Comment by perrier54** [comment]
I seem to have misunderstood @sylvainkahane 's proposal. I understood that the `Subject` feature is attached to the governor verb and not to the infinitive.
I agree with the proposal to attach the feature to the infinitive and prefer the more precise version, as it can be generalized to object raising like in the example _the book is tough to read_.  We can attach the feature `Object= SubjRaising` to _read_, assuming that the adjective does have _book_ as its subject.

**Comment by bguil** [comment]
SUD French data have been updated but, when there is no overt raised subject:
 * [ParisStories](http://universal.grew.fr/?corpus=SUD_French-ParisStories@latest&custom=63553c41dbcc7) and [Rhapsodie](http://universal.grew.fr/?corpus=SUD_French-Rhapsodie@latest&custom=63553c41dbcc7) use `Subject=NoRaising`
 * [GSD](http://universal.grew.fr/?corpus=SUD_French-GSD@latest&custom=63553c41dbcc7) uses `Subject=Generic`

It is needed to decide one solution and to make corpora consistent.
