### ISSUE TITLE
multiword expressions and titles

### ISSUE THREAD

**Issue by perrier54** [surfacesyntacticud/guidelines#4]
Multi-word expressions (MWEs) and titles have the following property in common: their internal structure is not naturally integrated into the syntactic structure of the sentence; they are double-sided objects: on the one hand, they behave as atomic objects with the rest of the sentence, and on the other hand, they behave as a structure with its elements, and there is a break between the atomic object and the structure. To express the first aspect, we need to define the interface of a MWE or title with the rest of the sentence.

**1. The interface with the rest of the sentence**
The interface is attached to the head of the MWE or title. It has an  _ExtPos_ feature, which gives the POS of the expression towards the rest of the sentence. 

> Example:  for the MWE _tout de suite_, the head is _de_, which has a feature _Ext_Pos = ADV_, because the MWE behaves like an adverb towards the rest of the sentence.

For titles, the _Extpos_ feature has the value _PROPN_, because titles behave like proper nouns towards the rest of the sentence.

The head of a MWE or title has another feature, _Type_, with the possible values  _MWE_ or _Title_.

The _Extpos_ and _Type_ features are also used for tokens that do not behave with their usual POS.  In this case, the value of _Type_ is _Conv_. In the _[SUD_French-GSD](https://github.com/surfacesyntacticud/SUD_French-GSD)_ corpus, this possibility is used to replace the _SYM_ POS with the actual POS played by a symbol in the sentence.

>  Example:  in _20 %_, the POS of _%_ is _SYM_ and its _ExtPos_ _NOUN_.

**2. The internal structure of a title or MWE**
A title is structured as any phrase. We have only to mark the elements of the title different from the head to distinguish them from the external dependents of the title head. They are marked with the feature _InTitle = Yes_.

For MWE, it is the internal relations and not the internal tokens that are marked in the current French corpora. They are marked with the _@fixed_ deep feature.   
Since only one deep feature can be used, other deep features cannot be used in MWEs, which limits the ability to express certain properties within MWEs.

> Example: in the prepositional locution _"il y a" (ago)_, _"il"_ is the impersonal subject of _"a",_ which is normally indicated with the _@expl_ feature on the subject relation between _"a"_ and "il".  Unfortunately, this is not possible because there is already a deep feature, _@fixed_.

I propose to mark the tokens inside a MWE with the feature _InMWE = Yes_ instead of marking  relations,  which frees a possibility for deep features on the relations.

Some MWEs do not have an internal syntax structure. In this case, the head is chosen as the left-most token of the MWE. In current French corpora, all elements of the MWE are linked in a left-to-right chain with _unk@fixed_ relations.

To be consistent with my previous suggestion, I propose to replace unk@fixed relations by simple unk relations and to mark the MWE elements with the feature _InMWE = Yes_

> Example: _tout de même (still)_
_tout[upos=PRON, extpos=ADV, Type=MWE] --[unk]-> de[upos=ADP,InMWE=Yes]
--[unk]->  même [upos=ADV,InMWE=Yes]_

**3. MWEs inside titles**
There is no problem when the head of the MWE is different from the head of the title. The specific features of the MWE can be added to the specific features of the title. For instance, the internal element of the MWE has both feature _InMWE = Yes_ and feature _InTitle = Yes_.
The problem arises when the head of the MWE is at the same time the head of the title. There is a conflict between the features _ExtPos_ and _Type_ features of the MWE and the title.  For _ExtPos_, I propose to keep the MWE feature because the title feature is always _PROPN_ and for _Type_, I propose to add a new type, _MWE-Title_.

> Example: _à propos d'Henry (Regarding Henry - title of an American film)_ 
_à [upos=ADP, Extpos=ADV, Type=MWE-Title]  --[comp:obj]-> propos[upos=NOUN, InMWE=Yes,InTitle=Yes] ..._

**Comment by kimgerdes** [comment]
in the UD page about MWE there are a few interesting examples and opinions that we could take into consideration when writing our MWE SUD guide
https://universaldependencies.org/workgroups/mwe.html

**Comment by sylvainkahane** [comment]
When _il y a_ is used as an ADP, it doesn't make sense, in my opinion, to indicate  that _il_ is an expletive. The verb _a_ has no longer a separate meaning.

The feature `@fixed` on the relation and the feature `InMWE=Yes` on the dependent are absolutely equivalent and thus redundant. It's not a problem. Personally I like the feature `@fixed`, because relation into idioms tend to frozen. For example, in the very old idiom _(aller) tambour battant_, _tambour_ is the object of _battant_, which in Old French was allowed to be before the verb.

**Comment by perrier54** [comment]
I prefer `INMWE = Yes` to `@fixed` for three reasons:

1. The label `fixed`is already used in UD with more restrictions, especially with only continuous MWEs.
2. The property of being fixed is a property of the whole expression and not of each relation individually; therefore, there is no more reason to mark relations than tokens.
3. The notation `INMWE = Yes` is homogeonous with that of titles.

**Comment by perrier54** [comment]
At the end of a meeting of several people involved in the development of SUD, we made the following proposals : 

1. Mark the MWE internal tokens rather the MWE internal relations
2. Choose a more appropriate term than MWE for the expressions concerned; the term "idiom" has been proposed. If this term were adopted, each token belonging to an MWE would be marked with `InIdiom=Yes` and the head would be marked with `PhraseType=Idiom`.
3. For consistency, title heads would be marked with `PhraseType=Title`.
4. For tokens that are used with a POS other than their usual POS, an ExtPos feature would give the POS used.

**Comment by bguil** [comment]
The CoNLL columns `FEATS` (the 5th column in usual CoNLL) should be used for morphosyntactic features.

The new features related to MWE and titles (`ExtPos`, `InIdiom`, `PhraseType`…) should be put in the `MISC` column (the 10th column).

For instance, in `SUD_French-GSD`:

```
# sent_id = fr-ud-train_06849
# text = Pourquoi se gêner ?
1	Pourquoi	pourquoi	ADV	_	_	3	mod	_	wordform=pourquoi
2	se	se	PRON	_	Person=3|PronType=Prs	3	comp	_	InIdiom=Yes
3	gêner	gêner	VERB	_	VerbForm=Inf	0	root	_	ExtPos=VERB|PhraseType=Idiom
4	?	?	PUNCT	_	_	3	punct	_	_

```

**Comment by bguil** [comment]
These decisions are reported in the [guidelines](https://surfacesyntacticud.github.io/guidelines/u/particular_phenomena/idioms_titles/).
