### ISSUE TITLE
add correct link to url in github page

### ISSUE THREAD

**Issue by kirianguiller** [surfacesyntacticud/guidelines#50]
Hi, 

We could try to add the link to https://guidelines.surfacesyntacticud.org/ in the meta of the main page of this github (on the right of the page, see image below). It seems that I don't have the right to change this info but maybe @bguil has it.

![image](https://github.com/surfacesyntacticud/guidelines/assets/35531073/007c3a48-e28e-43f3-9032-ac378a1c5620)

Thanks

**Comment by bguil** [comment]
done
