### ISSUE TITLE
VERB / ADJ

### ISSUE THREAD

**Issue by bguil** [surfacesyntacticud/guidelines#7]
In **SUD_French-GSD**, construction like *est situé* is wrongly annotated in many cases ([Grew-match](http://match.grew.fr/?corpus=SUD_French-GSD@2.6&custom=5f685cf4e3479&clustering=e.label)).

In most of the cases, the relation is `comp:aux@tense` is used. This  is wrong because the whole sentence is in a present tense. For instance:

> *L'ambassade est située à Paris.*

![Screenshot 2020-09-21 at 10 21 16](https://user-images.githubusercontent.com/687155/93745668-32237d00-fbf4-11ea-838e-da6b2d947b3b.png)

Two options:

* **A**: *est* -[`comp:aux@pass`]-> *située*:`VERB`
* **B**: *est* -[`comp:pred`]-> *située*:`ADJ`

With @perrier54, we prefer solution **B** because it is not possible to have and active reformulation.

**Remarks**:
 * *situer* is used in a similar way as a modifier ([Grew-match](http://match.grew.fr/?corpus=SUD_French-GSD@latest&custom=5f68605038db6)) and should also be annotated as `ADJ` in these cases.

**Comment by Julie921** [comment]
In **SUD_French-GSD**, we have this annotation now : 
**B**: est -[comp:pred]-> située:**VERB**
See  http://universal.grew.fr/?custom=63f763da72f60
It is consistent, so I close this issue.
