### ISSUE TITLE
generic infinitive verbal forms

### ISSUE THREAD

**Issue by sylvainkahane** [surfacesyntacticud/guidelines#9]
In French or English, most infinitive verbal share their logical subject with another argument in the clause (raising or equi-construction), which is marked in SUD with the deep feature _@x_. In some cases, the infinitive verbal form does not and it has a generic interpretation:

```
il faut travailler plus
fumer n'est pas recommandé

```
I think that these rare cases should be marked rather than the default case. I propose to introduce a feature on generic verbal forms. It will be redundant with the absence of `@x`, but it will be more reliable.

**Comment by Julie921** [comment]
Obsolete annotation. See #29
